// Identifiants présents en dur dans src/web/index.html.
//
// Cette liste n'est pas décorative : `$()` n'accepte qu'un `StaticId`, ce qui
// lui permet de renvoyer un HTMLElement non-nullable. Tout élément créé à
// l'exécution (la landing est construite paresseusement) est donc rejeté par le
// type-check et doit passer par `$opt()`, qui rend la nullité explicite.
// C'est exactement ce qui manquait quand `render()` déréférençait
// `#landingStats` avec `?q=…` au chargement.
//
// Le test Rust `static_ids_match_index_html` garde cette union synchronisée
// avec index.html — sinon elle dérive en silence.

type StaticId =
  | "cmpAdd"
  | "cmpB"
  | "cmpBtn"
  | "cmpC"
  | "cmpClose"
  | "cmpDropC"
  | "cmpGlegend"
  | "cmpGo"
  | "cmpGraphCard"
  | "cmpResults"
  | "cmpSlotC"
  | "cmpSubject"
  | "cmpSubtitle"
  | "cmpTitle"
  | "cntCorr"
  | "cntPivots"
  | "cntSignals"
  | "cntSources"
  | "comparator"
  | "corr"
  | "elapsed"
  | "err"
  | "exClose"
  | "exGo"
  | "exHint"
  | "exOut"
  | "exText"
  | "exTitle"
  | "exportCsv"
  | "exportStix"
  | "extractBtn"
  | "extractor"
  | "glegend"
  | "goBtn"
  | "graphCard"
  | "histRow"
  | "icoMoon"
  | "icoSun"
  | "jsonBtn"
  | "kindBadge"
  | "landing"
  | "mTheme"
  | "obsCopy"
  | "obsText"
  | "pivots"
  | "progress"
  | "q"
  | "raw"
  | "rawCopy"
  | "rawWrap"
  | "report"
  | "sbarSignals"
  | "secCorr"
  | "secPivots"
  | "secSignals"
  | "secSources"
  | "selfNote"
  | "setClose"
  | "setEndpoints"
  | "setEndpointsSec"
  | "setEye"
  | "setKeys"
  | "setKeysSec"
  | "setMsg"
  | "setSave"
  | "setSources"
  | "setSourcesSec"
  | "setSourcesSum"
  | "setTitle"
  | "setToken"
  | "settings"
  | "settingsBtn"
  | "signals"
  | "skeleton"
  | "sources"
  | "srcErrList"
  | "srcErrSummary"
  | "srcErrWrap"
  | "themeBtn"
  | "tiles"
  | "toast"
  | "tokenBtn"
  | "verdict";
